import { type Order } from "../../types/order"

export const mockOrders: Order[] = [
  {
    _id: '507f1f77bcf86cd799439011',
    restaurantId: 'rest001',
    restaurantName: 'Nhà hàng Phở Hà Nội',
    items: [
      {
        menuItemId: 'item001',
        name: 'Phở bò',
        price: 45000,
        quantity: 2,
        image: 'https://via.placeholder.com/150?text=Pho',
      },
      {
        menuItemId: 'item002',
        name: 'Nước chanh',
        price: 15000,
        quantity: 2,
        image: 'https://via.placeholder.com/150?text=Drink',
      },
    ],
    totalPrice: 120000,
    status: 'delivering',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    deliveryAddress: '123 Đường Trần Hưng Đạo, Quận 1, TP.HCM',
    paymentMethod: 'Thanh toán khi nhận hàng',
  },
  {
    _id: '507f1f77bcf86cd799439012',
    restaurantId: 'rest002',
    restaurantName: 'KFC Vietnam',
    items: [
      {
        menuItemId: 'item101',
        name: 'Combo gà rán',
        price: 89000,
        quantity: 1,
        image: 'https://via.placeholder.com/150?text=KFC',
      },
    ],
    totalPrice: 120500,
    status: 'completed',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    deliveryAddress: '456 Đường Lê Lợi, Quận 1, TP.HCM',
    paymentMethod: 'Thanh toán bằng ngân hàng',
  },
  {
    _id: '507f1f77bcf86cd799439013',
    restaurantId: 'rest003',
    restaurantName: 'Pizza Hut',
    items: [
      {
        menuItemId: 'item201',
        name: 'Pizza Pepperoni',
        price: 150000,
        quantity: 1,
        image: 'https://via.placeholder.com/150?text=Pizza',
      },
    ],
    totalPrice: 165500,
    status: 'canceled',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    deliveryAddress: '789 Đường Nguyễn Huệ, Quận 1, TP.HCM',
    paymentMethod: 'Thanh toán khi nhận hàng',
  },
  {
    _id: '507f1f77bcf86cd799439014',
    restaurantId: 'rest001',
    restaurantName: 'Nhà hàng Phở Hà Nội',
    items: [
      {
        menuItemId: 'item003',
        name: 'Bún chả',
        price: 55000,
        quantity: 1,
        image: 'https://via.placeholder.com/150?text=BunCha',
      },
      {
        menuItemId: 'item004',
        name: 'Gỏi cuốn',
        price: 35000,
        quantity: 2,
        image: 'https://via.placeholder.com/150?text=GoiCuon',
      },
    ],
    totalPrice: 130000,
    status: 'pending',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    deliveryAddress: '321 Đường Cộng Hòa, Quận Tân Bình, TP.HCM',
    paymentMethod: 'Thanh toán khi nhận hàng',
  },
  {
    _id: '507f1f77bcf86cd799439015',
    restaurantId: 'rest002',
    restaurantName: 'KFC Vietnam',
    items: [
      {
        menuItemId: 'item102',
        name: 'Cơm gà chiên',
        price: 65000,
        quantity: 1,
        image: 'https://via.placeholder.com/150?text=ComGa',
      },
    ],
    totalPrice: 80500,
    status: 'completed',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    deliveryAddress: '654 Đường Phạm Ngũ Lão, Quận 1, TP.HCM',
    paymentMethod: 'Thanh toán khi nhận hàng',
  },
]
