module.exports = {
  // --- OAuth/Token Errors (Giữ lại) ---
  BAD_OAUTH_STATE: 'BAD_OAUTH_STATE',
  PROVIDER_MISMATCH: 'PROVIDER_MISMATCH',
  AUTH_MISSING_REFRESH_TOKEN: 'AUTH_MISSING_REFRESH_TOKEN',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_MISSING_ACCESS_TOKEN: 'AUTH_MISSING_ACCESS_TOKEN',
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  TOKEN_GENERATION_FAILED: 'TOKEN_GENERATION_FAILED',

  // --- Hành động Bổ sung (Status Code 202) ---
  REQUIRE_PHONE_USERNAME_PASSWORD: 'REQUIRE_PHONE_USERNAME_PASSWORD',

  // --- Lỗi Đăng nhập & Xác thực (Bổ sung/Thay thế) ---
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_MISSING_FIELDS: 'AUTH_MISSING_FIELDS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',

  // --- Lỗi logic xử lí ---
  USER_HASH_FAILED: 'USER_HASH_FAILED',

  // --- Lỗi Người dùng & Ủy quyền ---
  AUTH_ACCESS_DENIED: 'AUTH_ACCESS_DENIED', // 403 Forbidden
  USER_INACTIVE: 'USER_INACTIVE',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED', // dùng khi thiếu thông tin
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  // --- Lỗi người dùng
  USER_INVALID_UPDATE_FIELDS: 'USER_INVALID_UPDATE_FIELDS',
  USER_PROFILE_NOT_FOUND: 'USER_PROFILE_NOT_FOUND',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED', // Cập nhật thất bại
  USER_DELETE_FAILED: 'USER_DELETE_FAILED', // Xóa tài khoản thất bại
  USER_PASSWORD_INCORRECT: 'USER_PASSWORD_INCORRECT', // Mật khẩu cũ sai khi đổi mật khẩu
  USER_UNAUTHORIZED_ACTION: 'USER_UNAUTHORIZED_ACTION', // Không đủ quyền thực hiện hành động

  // --- Restaurant Errors ---
  RESTAURANT_NOT_FOUND: 'RESTAURANT_NOT_FOUND',
  RESTAURANT_INACTIVE: 'RESTAURANT_INACTIVE',
  RESTAURANT_ALREADY_EXISTS: 'RESTAURANT_ALREADY_EXISTS',
  RESTAURANT_UPDATE_FAILED: 'RESTAURANT_UPDATE_FAILED',
  RESTAURANT_DELETE_FAILED: 'RESTAURANT_DELETE_FAILED',
  RESTAURANT_UNAUTHORIZED_ACTION: 'RESTAURANT_UNAUTHORIZED_ACTION',
  RESTAURANT_INVALID_INPUT: 'RESTAURANT_INVALID_INPUT',
  RESTAURANT_OUT_OF_SERVICE_AREA: 'RESTAURANT_OUT_OF_SERVICE_AREA',

  // --- MenuItem Errors ---
  MENUITEM_NOT_FOUND: 'MENUITEM_NOT_FOUND',
  MENUITEM_INACTIVE: 'MENUITEM_INACTIVE',
  MENUITEM_CREATE_FAILED: 'MENUITEM_CREATE_FAILED',
  MENUITEM_UPDATE_FAILED: 'MENUITEM_UPDATE_FAILED',
  MENUITEM_DELETE_FAILED: 'MENUITEM_DELETE_FAILED',
  MENUITEM_INVALID_OPTION: 'MENUITEM_INVALID_OPTION',
  MENUITEM_INVALID_CATEGORY: 'MENUITEM_INVALID_CATEGORY',
  MENUITEM_UNAVAILABLE: 'MENUITEM_UNAVAILABLE',

  // --- Cart Errors ---
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_ITEM_INVALID: 'CART_ITEM_INVALID',
  CART_RESTAURANT_CONFLICT: 'CART_RESTAURANT_CONFLICT', // đưa món từ quán khác vào
  CART_EMPTY: 'CART_EMPTY',

  // --- Order Errors ---
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_CREATE_FAILED: 'ORDER_CREATE_FAILED',
  ORDER_PAYMENT_REQUIRED: 'ORDER_PAYMENT_REQUIRED',
  ORDER_ALREADY_PAID: 'ORDER_ALREADY_PAID',
  ORDER_INVALID_STATUS: 'ORDER_INVALID_STATUS',

  // --- Payment Errors ---
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_METHOD_NOT_SUPPORTED: 'PAYMENT_METHOD_NOT_SUPPORTED',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  PAYMENT_REFUND_FAILED: 'PAYMENT_REFUND_FAILED',

  // --- Lỗi Chung (Bổ sung) ---
  SERVER_INTERNAL_ERROR: 'SERVER_INTERNAL_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INVALID_INPUT: 'INVALID_INPUT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};