module.exports = {
  /* =======================
   * OAuth / Token Errors
   * ======================= */
  BAD_OAUTH_STATE: 'BAD_OAUTH_STATE',
  PROVIDER_MISMATCH: 'PROVIDER_MISMATCH',

  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_MISSING_ACCESS_TOKEN: 'AUTH_MISSING_ACCESS_TOKEN',
  AUTH_MISSING_REFRESH_TOKEN: 'AUTH_MISSING_REFRESH_TOKEN',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  TOKEN_GENERATION_FAILED: 'TOKEN_GENERATION_FAILED',

  /* =======================
   * Authentication Errors
   * ======================= */
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_MISSING_FIELDS: 'AUTH_MISSING_FIELDS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_PERMISSION_DENIED: 'AUTH_PERMISSION_DENIED',

  /* =======================
   * Special Action / Status
   * ======================= */
  REQUIRE_PHONE_USERNAME_PASSWORD: 'REQUIRE_PHONE_USERNAME_PASSWORD', // 202 Accepted

  /* =======================
   * User Errors
   * ======================= */
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_INACTIVE: 'USER_INACTIVE',
  USER_BANNED: 'USER_BANNED',

  USER_INVALID_UPDATE_FIELDS: 'USER_INVALID_UPDATE_FIELDS',
  USER_PROFILE_NOT_FOUND: 'USER_PROFILE_NOT_FOUND',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',
  USER_DELETE_FAILED: 'USER_DELETE_FAILED',
  USER_PASSWORD_INCORRECT: 'USER_PASSWORD_INCORRECT',
  USER_UNAUTHORIZED_ACTION: 'USER_UNAUTHORIZED_ACTION',

  /* =======================
   * Validation / Logic Errors
   * ======================= */
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_INPUT: 'INVALID_INPUT',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  USER_HASH_FAILED: 'USER_HASH_FAILED',

  /* =======================
   * Restaurant Errors
   * ======================= */
  RESTAURANT_NOT_FOUND: 'RESTAURANT_NOT_FOUND',
  RESTAURANT_ALREADY_EXISTS: 'RESTAURANT_ALREADY_EXISTS',
  RESTAURANT_INACTIVE: 'RESTAURANT_INACTIVE',

  RESTAURANT_UPDATE_FAILED: 'RESTAURANT_UPDATE_FAILED',
  RESTAURANT_DELETE_FAILED: 'RESTAURANT_DELETE_FAILED',
  RESTAURANT_UNAUTHORIZED_ACTION: 'RESTAURANT_UNAUTHORIZED_ACTION',
  RESTAURANT_INVALID_INPUT: 'RESTAURANT_INVALID_INPUT',

  RESTAURANT_OUT_OF_SERVICE_AREA: 'RESTAURANT_OUT_OF_SERVICE_AREA',
  RESTAURANT_OUTSIDE_BUSINESS_HOURS: 'RESTAURANT_OUTSIDE_BUSINESS_HOURS',
  RESTAURANT_NOT_ACCEPTING_ORDERS: 'RESTAURANT_NOT_ACCEPTING_ORDERS',
  RESTAURANT_NOT_OWNER: 'RESTAURANT_NOT_OWNER',

  /* =======================
   * Menu Item Errors
   * ======================= */
  MENUITEM_NOT_FOUND: 'MENUITEM_NOT_FOUND',
  MENUITEM_INACTIVE: 'MENUITEM_INACTIVE',

  MENUITEM_CREATE_FAILED: 'MENUITEM_CREATE_FAILED',
  MENUITEM_UPDATE_FAILED: 'MENUITEM_UPDATE_FAILED',
  MENUITEM_DELETE_FAILED: 'MENUITEM_DELETE_FAILED',

  MENUITEM_INVALID_OPTION: 'MENUITEM_INVALID_OPTION',
  MENUITEM_INVALID_CATEGORY: 'MENUITEM_INVALID_CATEGORY',
  MENUITEM_UNAVAILABLE: 'MENUITEM_UNAVAILABLE',

  /* =======================
   * Cart Errors
   * ======================= */
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_ITEM_INVALID: 'CART_ITEM_INVALID',
  CART_RESTAURANT_CONFLICT: 'CART_RESTAURANT_CONFLICT',
  CART_EMPTY: 'CART_EMPTY',

  /* =======================
   * Order Errors
   * ======================= */
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_CREATE_FAILED: 'ORDER_CREATE_FAILED',

  ORDER_PAYMENT_REQUIRED: 'ORDER_PAYMENT_REQUIRED',
  ORDER_ALREADY_PAID: 'ORDER_ALREADY_PAID',

  ORDER_INVALID_STATUS: 'ORDER_INVALID_STATUS',
  ORDER_NOT_OWNER: 'ORDER_NOT_OWNER',
  ORDER_NOT_RESTAURANT: 'ORDER_NOT_RESTAURANT',

  ORDER_CANNOT_CANCEL: 'ORDER_CANNOT_CANCEL',
  ORDER_CANNOT_CHANGE_STATUS: 'ORDER_CANNOT_CHANGE_STATUS',
  ORDER_CANNOT_CHANGE_INFO: 'ORDER_CANNOT_CHANGE_INFO',

  /* =======================
   * Payment Errors
   * ======================= */
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_METHOD_NOT_SUPPORTED: 'PAYMENT_METHOD_NOT_SUPPORTED',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  PAYMENT_REFUND_FAILED: 'PAYMENT_REFUND_FAILED',

  /* =======================
   * Common / System Errors
   * ======================= */
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SERVER_INTERNAL_ERROR: 'SERVER_INTERNAL_ERROR',
};