module.exports = {
  // --- OAuth/Token Errors (Giữ lại) ---
  BAD_OAUTH_STATE: 'BAD_OAUTH_STATE',
  PROVIDER_MISMATCH: 'PROVIDER_MISMATCH',
  AUTH_MISSING_REFRESH_TOKEN: 'AUTH_MISSING_REFRESH_TOKEN',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_MISSING_ACCESS_TOKEN: 'AUTH_MISSING_ACCESS_TOKEN',
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  TOKEN_GENERATION_FAILED: 'TOKEN_GENERATION_FAILED',

  // --- Hành động Bổ sung (Status Code 202) ---
  REQUIRE_PHONE_USERNAME_PASSWORD: 'REQUIRE_PHONE_USERNAME_PASSWORD',

  // --- Lỗi Đăng nhập & Xác thực (Bổ sung/Thay thế) ---
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_MISSING_FIELDS: 'AUTH_MISSING_FIELDS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',

  // --- Lỗi logic xử lí ---
  USER_HASH_FAILED: 'USER_HASH_FAILED',

  // --- Lỗi Người dùng & Ủy quyền ---
  AUTH_ACCESS_DENIED: 'AUTH_ACCESS_DENIED', // 403 Forbidden
  USER_INACTIVE: 'USER_INACTIVE',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED', // dùng khi thiếu thông tin
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  // --- Lỗi người dùng
  USER_PROFILE_NOT_FOUND: 'USER_PROFILE_NOT_FOUND',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED', // Cập nhật thất bại
  USER_DELETE_FAILED: 'USER_DELETE_FAILED', // Xóa tài khoản thất bại
  USER_PASSWORD_INCORRECT: 'USER_PASSWORD_INCORRECT', // Mật khẩu cũ sai khi đổi mật khẩu
  USER_UNAUTHORIZED_ACTION: 'USER_UNAUTHORIZED_ACTION', // Không đủ quyền thực hiện hành động

  // --- Lỗi Chung (Bổ sung) ---
  SERVER_INTERNAL_ERROR: 'SERVER_INTERNAL_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INVALID_INPUT: 'INVALID_INPUT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};